<h2>About us</h2>
The Team
Kevin Systrom (CEO, co-founder)

Kevin (@kevin) graduated from Stanford University in 2006 with a BS in Management Science & Engineering. He got his first taste of the startup world when he was an intern at Odeo that later became Twitter. He spent two years at Google - the first of which was working on Gmail, Google Reader, and other products and the latter where he worked on the Corporate Development team. Kevin has always had a passion for social products that enable people to communicate more easily, and combined with his passion for photography Instagram is a natural fit.
Mike Krieger (co-founder)

Mike (@mikeyk) also graduated from Stanford University where he studied Symbolic Systems with a focus in Human-Computer Interaction. During his undergrad, he interned at Microsoft's PowerPoint team as a PM and at Foxmarks (now Xmarks) as a software developer. He wrote his Master's thesis on how user interfaces can better support collaboration on a large scale. After graduating, he worked at Meebo for a year and a half as a user experience designer and as a front-end engineer before joining the Instagram team doing design & development.