<h2>Services</h2>
Services is a standardized API for Drupal that allows you to create "services", or a collection of methods, intended for consumption by remote applications. Several "servers", or protocols, provide different ways to call these methods from a remote site. It works similar to the existing XMLRPC capabilities of Drupal, but provides additional functionality like:

Pluggable "server" modules allowing for protocols other than XMLRPC (like SOAP, REST, AMF)
Pluggable "service" modules allowing developers to add additional remote services
Pluggable authentication mechanisms
A number of included service modules which interact with existing Drupal modules like node, taxonomy, user, views, and system

Who might be interested in Services?

Flash/Flex or JavaScript developers looking for the best backend CMS system.
Mobile developers wanting to integrate Drupal with an Android or iPhone application.
Anyone else looking to integrate external applications with Drupal.

Related projects

Related projects.

For community support and general discussion related to Services, visit the Services group on groups.drupal.org.