
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
      <?php echo $this->jQuery()
                        ->setVersion('1.10.2')
                        ->setUIVersion('1.9.2')
                        ->enable()
                        ->uiEnable()
                        ->addStylesheet('/css/smoothness/jquery-ui-1.9.2.custom.min.css');
      ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <base href="/" />
    <link rel="stylesheet" type="text/css" href="/css/master.css" />
    <link rel="stylesheet" type="text/css" href="/css/admin.css" />
    <script src="/js/form.js"></script>
      <script src="/js/autocomplete.js"></script>
      <script src="/js/scripts.js"></script>
  </head>
  <body>
    <div id="header">
      <div id="logo">
        <img src="/images/logo-admin.gif" />
      </div>
      


      </div>
    </div>
    
    <div id="content">

      <?php echo $this->layout()->content ?>
    </div>
   </body>
</html>
