<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title>Magic Admin. Advanced, Beautiful and Customizable Admin Template.</title>
       
        <!-- CSS Reset -->
		<link rel="stylesheet" type="text/css" href="/css/reset.css" tppabs="http://www.xooom.pl/work/magicadmin/css/reset.css" media="screen" />
       
        <!-- Fluid 960 Grid System - CSS framework -->
		<link rel="stylesheet" type="text/css" href="/css/grid.css" tppabs="http://www.xooom.pl/work/magicadmin/css/grid.css" media="screen" />
		
        <!-- IE Hacks for the Fluid 960 Grid System -->
        <!--[if IE 6]><link rel="stylesheet" type="text/css" href="ie6.css" tppabs="http://www.xooom.pl/work/magicadmin/css/ie6.css" media="screen" /><![endif]-->
		<!--[if IE 7]><link rel="stylesheet" type="text/css" href="ie.css" tppabs="http://www.xooom.pl/work/magicadmin/css/ie.css" media="screen" /><![endif]-->
        
        <!-- Main stylesheet -->
        <link rel="stylesheet" type="text/css" href="/css/styles.css" tppabs="http://www.xooom.pl/work/magicadmin/css/styles.css" media="screen" />
        
        <!-- WYSIWYG editor stylesheet -->
        <link rel="stylesheet" type="text/css" href="/css/jquery.wysiwyg.css" tppabs="http://www.xooom.pl/work/magicadmin/css/jquery.wysiwyg.css" media="screen" />
        
        <!-- Table sorter stylesheet -->
        <link rel="stylesheet" type="text/css" href="/css/tablesorter.css" tppabs="http://www.xooom.pl/work/magicadmin/css/tablesorter.css" media="screen" />
        
        <!-- Thickbox stylesheet -->
        <link rel="stylesheet" type="text/css" href=/css/"thickbox.css" tppabs="http://www.xooom.pl/work/magicadmin/css/thickbox.css" media="screen" />
        
        <!-- Themes. Below are several color themes. Uncomment the line of your choice to switch to different color. All styles commented out means blue theme. -->
        <link rel="stylesheet" type="text/css" href="/css/theme-blue.css" tppabs="http://www.xooom.pl/work/magicadmin/css/theme-blue.css" media="screen" />
        <!--<link rel="stylesheet" type="text/css" href="css/theme-red.css" media="screen" />-->
        <!--<link rel="stylesheet" type="text/css" href="css/theme-yellow.css" media="screen" />-->
        <!--<link rel="stylesheet" type="text/css" href="css/theme-green.css" media="screen" />-->
        <!--<link rel="stylesheet" type="text/css" href="css/theme-graphite.css" media="screen" />-->
        
		<!-- JQuery engine script-->
		<script type="text/javascript" src="/js/admin-css/jquery-1.3.2.min.js"></script>
        
		<!-- JQuery WYSIWYG plugin script -->
		<script type="text/javascript" src="/js/admin-css/jquery.wysiwyg.js"></script>
        
        <!-- JQuery tablesorter plugin script-->
		<script type="text/javascript" src="/js/admin-css/jquery.tablesorter.min.js"></script>
        
		<!-- JQuery pager plugin script for tablesorter tables -->
		<script type="text/javascript" src="/js/admin-css/jquery.tablesorter.pager.js"></script>
        
		<!-- JQuery password strength plugin script -->
		<script type="text/javascript" src="/js/admin-css/jquery.pstrength-min.1.2.js"></script>
        
		<!-- JQuery thickbox plugin script -->
		<script type="text/javascript" src="/js/admin-css/jthickbox.js"></script>
        
        <!-- Initiate WYIWYG text area -->
		<script type="text/javascript">
			$(function()
			{
			$('#wysiwyg').wysiwyg(
			{
			controls : {
			separator01 : { visible : true },
			separator03 : { visible : true },
			separator04 : { visible : true },
			separator00 : { visible : true },
			separator07 : { visible : false },
			separator02 : { visible : false },
			separator08 : { visible : false },
			insertOrderedList : { visible : true },
			insertUnorderedList : { visible : true },
			undo: { visible : true },
			redo: { visible : true },
			justifyLeft: { visible : true },
			justifyCenter: { visible : true },
			justifyRight: { visible : true },
			justifyFull: { visible : true },
			subscript: { visible : true },
			superscript: { visible : true },
			underline: { visible : true },
            increaseFontSize : { visible : false },
            decreaseFontSize : { visible : false }
			}
			} );
			});
        </script>
        
        <!-- Initiate tablesorter script -->
        <script type="text/javascript">
			$(document).ready(function() { 
				$("#myTable") 
				.tablesorter({
					// zebra coloring
					widgets: ['zebra'],
					// pass the headers argument and assing a object 
					headers: { 
						// assign the sixth column (we start counting zero) 
						6: { 
							// disable it by setting the property sorter to false 
							sorter: false 
						} 
					}
				}) 
			.tablesorterPager({container: $("#pager")}); 
		}); 
		</script>
        
        <!-- Initiate password strength script -->
		<script type="text/javascript">
			$(function() {
			$('.password').pstrength();
			});
        </script>
	</head>
	<body>
    	<!-- Header -->
        <div id="header">
            <!-- Header. Status part -->
            <div id="header-status">
                <div class="container_12">
                    <div class="grid_8">
					&nbsp;
                    </div>
                    <div class="grid_4">
                        <a href="" id="logout">
                        Logout
                        </a>
                    </div>
                </div>
                <div style="clear:both;"></div>
            </div> <!-- End #header-status -->
            
            <!-- Header. Main part -->
            <div id="header-main">
                <div class="container_12">
                    <div class="grid_12">
                        <div id="logo">
                            <ul id="nav">
                                <li id="current"><a href="">Dashboard</a></li>
                                <li><a href="">Articles</a></li>
                                <li><a href="">Files</a></li>
                                <li><a href="">Profile</a></li>
                                <li><a href="">Settings</a></li>
                            </ul>
                        </div><!-- End. #Logo -->
                    </div><!-- End. .grid_12-->
                    <div style="clear: both;"></div>
                </div><!-- End. .container_12 -->
            </div> <!-- End #header-main -->
            <div style="clear: both;"></div>
            <!-- Sub navigation -->
            <div id="subnav">
                <div class="container_12">
                    <div class="grid_12">
                        <ul>
                            <li><a href="#">link 1</a></li>
                            <li><a href="#">link 2</a></li>
                            <li><a href="#">link 3</a></li>
                            <li><a href="#">link 4</a></li>
                            <li><a href="#">link 5</a></li>
                        </ul>
                        
                    </div><!-- End. .grid_12-->
                </div><!-- End. .container_12 -->
                <div style="clear: both;"></div>
            </div> <!-- End #subnav -->
        </div> <!-- End #header -->
        
		<div class="container_12">
        

            
            <!-- Dashboard icons -->
            <div class="grid_7">
            	<a href="<?php echo $this->url(array(), 'admin-catalog-index');?>" class="dashboard-module">
                	<img src="/images/addbook.gif" width="64" height="64" alt="edit" />
                	<span>Add book</span>
                </a>

            	<a href="<?php echo $this->url(array(), 'admin-catalog-add-author'); ?>" class="dashboard-module">
                	<img src="/images/Crystal_Clear_user.gif" width="64" height="64" alt="edit" />
                	<span>Add author</span>
                </a>
                
                <a href="<?php echo $this->url(array(), 'admin-catalog-category');?>" class="dashboard-module">
                	<img src="/images/addcategory.gif" width="64" height="64" alt="edit" />
                	<span>Add Category</span>
                </a>
                
                <a href="<?php echo $this->url(array(), 'admin-catalog-publisher');?>" class="dashboard-module">
                	<img src="/images/publish-icon.png" width="64" height="64" alt="edit" />
                	<span>Add Publisher</span>
                </a>
                
                <div style="clear: both"></div>
            </div> <!-- End .grid_7 -->
            
            
            <div style="clear:both;"></div>
            
            
            
            <div class="grid_12" style ="display:none">
                
                <!-- Notification boxes -->
                <span class="notification n-success">Success notification.</span>
                
                <span class="notification n-information">Information notification.</span>
                
                <span class="notification n-attention">Attention notification.</span>
                
                <span class="notification n-error">Error notification.</span>
                
                
                <div class="bottom-spacing">
                
                    <!-- Button -->
                    <div class="float-right">
                        <a href="" class="button">
                        	<span>New Article <img src="/images/plus-small.gif" tppabs="http://www.xooom.pl/work/magicadmin/images/plus-small.gif" width="12" height="9" alt="New article" /></span>
                        </a>
                    </div>
                    
                    <!-- Table records filtering -->
                    Filter: 
                    <select class="input-short">
                    	<option value="1" selected="selected">Select filter</option>
                        <option value="2">Created last week</option>
                        <option value="3">Created last month</option>
                        <option value="4">Edited last week</option>
                        <option value="5">Edited last month</option>
                    </select>
                    
                </div>
                
                
                <!-- Example table -->
                <div class="module">
                	<h2><span>Sample table</span></h2>
                    
                    <div class="module-table-body">
                    	<form action="">
                        <table id="myTable" class="tablesorter">
                        	<thead>
                                <tr>
                                    <th style="width:5%">#</th>
                                    <th style="width:20%">Title</th>
                                    <th style="width:21%">Author</th>
                                    <th style="width:13%">Category</th>
                                    <th style="width:13%">Pages</th>
                                    <th style="width:13%">Price</th>
                                    <th style="width:15%"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="align-center">1</td>
                                    <td><a href="">Don Quixote</a></td>
                                    <td>Cervantes</td>
                                    <td>adventure</td>
                                    <td>992</td>
                                    <td>$11.55</td>
                                    <td>
                                    	<input type="checkbox" />
                                        <a href=""><img src="/images/tick-circle.gif"  width="16" height="16" alt="published" /></a>
                                        <a href=""><img src="/images/pencil.gif"  width="16" height="16" alt="edit" /></a>
                                        <a href=""><img src="/images/balloon.gif" width="16" height="16" alt="comments" /></a>
                                        <a href=""><img src="/images/bin.gif"  width="16" height="16" alt="delete" /></a>
                                    </td>
                                </tr>
                               
                                    	<input type="checkbox" />
                                        <a href=""><img src="/images/tick-circle.gif" width="16" height="16" alt="published" /></a>
                                        <a href=""><img src="/images/pencil.gif"  width="16" height="16" alt="edit" /></a>
                                        <a href=""><img src="/images/balloon.gif"  width="16" height="16" alt="comments" /></a>
                                        <a href=""><img src="/images/bin.gif"  width="16" height="16" alt="delete" /></a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        </form>
                        <div class="pager" id="pager">
                            <form action="">
                                <div>
                                <img class="first" src="/images/arrow-stop-180.gif" alt="first"/>
                                <img class="prev" src="images/arrow-180.gif"  alt="prev"/> 
                                <input type="text" class="pagedisplay input-short align-center"/>
                                <img class="next" src="images/arrow.gif"  alt="next"/>
                                <img class="last" src="images/arrow-stop.gif"  alt="last"/> 
                                <select class="pagesize input-short align-center">
                                    <option value="10" selected="selected">10</option>
                                    <option value="20">20</option>
                                    <option value="30">30</option>
                                    <option value="40">40</option>
                                </select>
                                </div>
                            </form>
                        </div>
                        <div class="table-apply">
                            <form action="">
                            <div>
                            <span>Apply action to selected:</span> 
                            <select class="input-medium">
                                <option value="1" selected="selected">Select action</option>
                                <option value="2">Publish</option>
                                <option value="3">Unpublish</option>
                                <option value="4">Delete</option>
                            </select>
                            </div>
                            </form>
                        </div>
                        <div style="clear: both"></div>
                     </div> <!-- End .module-table-body -->
                </div> <!-- End .module -->
                
                
                     <div class="pagination">           
                		<a href="" class="button"><span><img src="/images/arrow-stop-180-small.gif" height="9" width="12" alt="First" /> First</span></a> 
                        <a href="" class="button"><span><img src="/images/arrow-180-small.gif" height="9" width="12" alt="Previous" /> Prev</span></a>
                        <div class="numbers">
                            <span>Page:</span> 
                            <a href="">1</a> 
                            <span>|</span> 
                            <a href="">2</a> 
                            <span>|</span> 
                            <span class="current">3</span> 
                            <span>|</span> 
                            <a href="">4</a> 
                            <span>|</span> 
                            <a href="">5</a> 
                            <span>|</span> 
                            <a href="">6</a> 
                            <span>|</span> 
                            <a href="">7</a> 
                            <span>|</span> 
                            <span>...</span> 
                            <span>|</span> 
                            <a href="">99</a>
                        </div> 
                        <a href="" class="button"><span>Next <img src="/images/arrow-000-small.gif"  height="9" width="12" alt="Next" /></span></a> 
                        <a href="" class="button last"><span>Last <img src="/images/arrow-stop-000-small.gif"  height="9" width="12" alt="Last" /></span></a>
                        <div style="clear: both;"></div> 
                     </div>
                
                

                
			</div> <!-- End .grid_12 -->
                
            <div style="clear:both;"></div>
            
            <!-- Form elements -->    
            <div class="grid_12">
            
                <div class="module">

                     <h2><span>Form</span></h2>
                        
                     <div class="module-body">
                     <?=$this->form?>
                        <form action="">
                        
                            <div>
                                <span class="notification n-success">Success notification.</span>
                            </div>
                            
                            <p>
                                <label>Short textfield</label>
                                <input type="text" class="input-short" />
                                <span class="notification-input ni-correct">This is correct, thanks!</span>
                            </p>
                            
                            <p>
                                <label>Medium textfield</label>
                                <input type="text" class="input-medium" />
                                <span class="notification-input ni-error">Sorry, try again.</span>
                            </p>
                            
                            
                            <p>
                                <label>Long textfield</label>
                                <input type="text" class="input-long" /><span class="notification-input ni-error">Sorry, try again.</span>
                            </p>
                            
                            <p>
                                <label>Short select input</label>
                                <select class="input-short">
                                    <option value="1">Option 1</option>
                                    <option value="2">Option 2</option>
                                    <option value="3">Option 3</option>
                                    <option value="4">Option 4</option>
                                </select>
                            </p>
                            
                            <p>
                                <label>Medium select input</label>
                                <select class="input-medium">
                                    <option value="1">Option 1</option>
                                    <option value="2">Option 2</option>
                                    <option value="3">Option 3</option>
                                    <option value="4">Option 4</option>
                                </select>
                            </p>
                            
                            <p>
                                <label>Long select input</label>
                                <select class="input-long">
                                    <option value="1">Option 1</option>
                                    <option value="2">Option 2</option>
                                    <option value="3">Option 3</option>
                                    <option value="4">Option 4</option>
                                </select>
                            </p>
                            
                            <p>
                                <label>Short text area</label>
                                <textarea rows="7" cols="90" class="input-short"></textarea>
                            </p>
                            
                            <p>
                                <label>Medium text area</label>
                                <textarea rows="7" cols="90" class="input-medium"></textarea>
                            </p>
                            
                            
                            <p>
                                <label>Long text area</label>
                                <textarea rows="7" cols="90" class="input-long"></textarea>
                            </p>
                                
                            <fieldset>
                                <legend>Checkboxes</legend>
                                <ul>
                                    <li><label><input type="checkbox" name="a" checked="checked" id="cb1" /> checkbox 1</label></li>
                                    <li><label><input type="checkbox" name="b" id="cb2" />  checkbox 2</label></li>
                                </ul>
                            </fieldset>
                            
                            <fieldset>
                                <legend>Radio buttons</legend>
                                <ul>
                                    <li><label><input type="radio" name="c" checked="checked" /> radio button 1</label></li>
                                    <li><label><input type="radio" name="c" /> radio button 2</label></li>
                                </ul>
                            </fieldset>
                            
                            <fieldset>
                                <label>Textarea with WYSIWYG</label>
                                <textarea id="wysiwyg" rows="11" cols="90" name="desc">    </textarea> 
                            </fieldset>
                            
                            <fieldset>
                                <input class="submit-green" type="submit" value="Submit" /> 
                                <input class="submit-gray" type="submit" value="Cancel" />
                            </fieldset>
                        </form>
                     </div> <!-- End .module-body -->

                </div>  <!-- End .module -->
        		<div style="clear:both;"></div>
            </div> <!-- End .grid_12 -->
                
           
            <div class="grid_6">
                <div class="module">
                     <h2><span>Password</span></h2>
                        
                     <div class="module-body">
                        <form action="">
                            <p>
                                <label>Type in new password</label>
                                <input class="input-medium password" type="password" />
                            </p>
                            <p>
                                <label>Repeat password</label>
                                <input type="password" class="input-medium" />
                            </p>
                            <fieldset>
                                <input class="submit-green" type="submit" value="Submit" /> 
                                <input class="submit-gray" type="submit" value="Cancel" />
                            </fieldset>
                        </form>
                        
                     </div> <!-- End .module-body -->
                </div> <!-- End .module -->
                <div style="clear:both;"></div>
            </div> <!-- End .grid_6 -->
            <div style="clear:both;"></div>
            
			<div class="grid_3">
				<h1>Heading 1</h1>
                <h2>Heading 2</h2>
                <h3>Heading 3</h3>
				<h4>Heading 4</h4>
                <h5>Heading 5</h5>
                <h6>Heading 6</h6>
            </div> <!-- End .grid_3 -->
            
            
            <div class="grid_3">
            	<p>Unordered list:</p>
                <ul class="bullets">
                	<li>UL Element 1</li>
                    <li>UL Element 2</li>
                    <li>UL Element 3</li>
                    <li>UL Element 4</li>
                    <li>UL Element 5</li>
                </ul>
            	<p>Ordered list:</p>
                <ol>
                	<li>OL Element 1</li>
                    <li>OL Element 2</li>
                    <li>OL Element 3</li>
                    <li>OL Element 4</li>
                    <li>OL Element 5</li>
                </ol>
            </div> <!-- End .grid_3 -->
            
            <div class="grid_6">
            	<p>Paragraph text:</p>
            
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vel nibh sit amet metus lacinia hendrerit. Nullam tempus sem ut quam luctus rhoncus. Nullam vitae justo ligula, nec sollicitudin mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam ut mauris quis sapien adipiscing porttitor vitae at mauris. Fusce imperdiet placerat nunc tincidunt varius. Quisque tempus, nibh ac tempus faucibus, elit lorem aliquam mauris, facilisis ornare nisl sapien eu mi. Vivamus ac tempor nulla. Fusce ac lectus sapien. Aliquam commodo urna nec leo tincidunt non ultrices augue consequat. Curabitur justo risus, placerat eu auctor et, scelerisque vitae velit. Mauris venenatis nisl ut elit congue in euismod libero ultrices. Duis tincidunt sagittis velit, in auctor elit molestie sit amet.</p> 
                
                <p>Vivamus tellus magna, malesuada ac cursus sed, facilisis non ligula. Nam porta ullamcorper nibh id sagittis. Mauris risus nisi, dictum eget feugiat in, egestas in diam. Nulla dictum pharetra bibendum. Morbi turpis sapien, dignissim congue dignissim in, laoreet non felis. Sed elit turpis, interdum cursus vulputate ut, consectetur eget odio. Morbi dolor velit, volutpat auctor aliquet id, auctor sit amet neque. Curabitur id quam sit amet est sagittis posuere. Sed a nunc eros, hendrerit pulvinar felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eget felis eget neque tristique scelerisque sed et magna.</p> 
                
            </div> <!-- End .grid_6 -->

            
            <div style="clear:both;"></div>
        </div> <!-- End .container_12 -->
		
           
        <!-- Footer -->
        <div id="footer">
        	<div class="container_12">
            	<div class="grid_12">
                	<!-- You can change the copyright line for your own -->
                	<p>&copy; 2010. <a href="http://www.templatescreme" title="Visit For More Free Website Templates">Free Website Templates</a></p>
        		</div>
            </div>
            <div style="clear:both;"></div>
        </div> <!-- End #footer -->
	</body>
/css/</html>

